exports.MESSAGES = {
    BAD_REQUEST: "Parameters not found",
    SERVER_ERROR: "Internal server error",
    VALIDATION: "Validation is not valid",
    AUTH_REQUIRE: "Authentication token required",
    INVALID_TOKEN: "Authentication token is not valid",
    VALID_TOKEN: "Authentication token is valid",
    BODY: "Please enter details",
    UPDATE_NOT: "Data not updated",
    UNAUTHORIZED_REQUEST: "You are not authorized for current action",
    EMPTY_PAYLOAD: "Payload is empty",
    DATA_NOT_FETCH: "Data not fetched",
    ID_NOT_FOUND: "Id not found",
    CUSTOMER_PAYMENT_DETAILS: {
        ADDED_SUCCESS: "Customer Payment Details create successfully",
        UPDATE_SUCCESS: "Customer Payment Details update successfully",
        ADDED_FAILED: "Failed to create customer Payment Details",
        FETCH_SUCCESS: "Customer Payment Details data fetched successfully",
        FETCH_FAILED: "Failed to fetch customer Payment Details data ",
        DETAILS_FETCH_SUCCESS:
            "Customer transaction details data fetched successfully",
        DETAILS_FETCH_FAILED: "Failed to fetch transaction details data ",
        CUSTOMER_ID_NOT_FOUND: "Please enter customerId",
        CUSTOMER_ID_NOT_FOUND: "Please enter customerId",
        STRIPE_FETCH_SUCCESS:
            "Customer stripe card Details data fetched successfully",
        STRIPE_FETCH_FAILED:
            "Failed to fetch customer stripe card Details data ",
        STRIPE_ADDED_SUCCESS: "Payment method card info saved successfully",
        STRIPE_ADDED_FAILED: "Failed to save payment method card info",
        STRIPE_DELETE_SUCCESS: "Payment method card info delete successfully",
        STRIPE_ACCOUNT_DELETE_SUCCESS: "Stripe account delete successfully",
        STRIPE_DELETE_FAILED: "Failed to delete payment method card info",
        STRIPE_CUSTOMER_ID_NOT_FOUND: "Please enter stripe customerId",
        STRIPE_CUSTOMER_CARD_ID_NOT_FOUND: "Please enter payment cardId",
        STRIPE_ACTION_REQUIRED: "Further action required",
        STRIPE_PAYMENT_CONFIRM: "Payment confirmed SuccessFully",
        STRIPE_INTENT_FAILED: "Failed to confirm Payment Intent",
        STRIPE_TRASACTION_DETAILS_ADD_SUCCESS:
            "Transaction details add successfully",
        TRASACTION_OR_MAIL_ERROR: "Notification or Email error",
        REVENUE_DETAILS_FETCHED: "Revenue details fetched successfully",
        REVENUE_DETAILS_FETCHED_FAILED: "Failed to fetch Revenue details",
        TRANSACTION_DETAILS_FETCHED: "Transaction details fetched successfully",
        TRANSACTION_DETAILS_FETCHED_FAILED:
            "Failed to fetch Transaction details",
    },
};

exports.STATUS_CODES = {
    // 1XX INFORMATIONAL
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    EARLY_HINTS: 103,

    // 2XX SUCCESS
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
    IM_USED: 226,

    // 3XX REDIRECTION
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,

    // 4XX CLIENT ERROR
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    UNPROCESSABLE_ENTITY: 422,
    VALIDATION_ERROR: 422,
    NOT_VALID_DATA: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    UNORDERED_COLLECTION: 425,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,

    // 5XX SERVER ERROR
    SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
};
