exports.MESSAGES = {
    BAD_REQUEST: "Parameters not found",
    SERVER_ERROR: "Internal server error",
    VALIDATION: "Validation is not valid",
    AUTH_REQUIRE: "Authentication token required",
    INVALID_TOKEN: "Authentication token is not valid",
    VALID_TOKEN: "Authentication token is valid",
    BODY: "Please enter details",
    UPDATE_NOT: "Data not updated",
    UNAUTHORIZED_REQUEST: "You are not authorized for current action",
    EMPTY_PAYLOAD: "Payload is empty",
    DATA_NOT_FETCH: "Data not fetched",
    ID_NOT_FOUND: "Id not found",
    USER: {
        IP_FETCHED: "Ip fetched successfully",
        NOT_FOUND: "User not found. Please check your email and try again.",
        FETCH_SUCCESS: "User info fetched successfully",
        FETCH_FAILED: "Failed to fetch User info",
        PASSWORD_INVALID:
            "Invalid password. Please check your password and try again.",
        INVALID_LINK:"Invalid link. Please check the link and try again.",
        UPDATE_SUCCESS: "User updated successfully",
        UPDATE_FAILED: "Failed to update User",
        NAME_NOT_ENTER: "Please enter name",
        EMAIL_NOT_ENTER: "Please enter email",
        ALREADY_EXIST: "User aleady exists",
        EMAIL_NOT_REGISTER: "User email not registered",
        DELETE_SUCCESS: "User delete successfully",
        DELETE_FAILED: "User delete failed",
        LOGIN: "Logged in!",
        MAIL_SENT: "Reset link has been successfully sent to the mail...",
        EMAIL_NOT_REGISTRED: "email is not registered with us....",
        PASSWORD_UPDATE: "User password updated successfully",
        TOKEN_NOT_EXIST: "User token is not exist",
        PASS_NOT_MATCH: "Your password is not matched!",
        EMAIL_NOT_MATCH: "Your email not matched",
        HASH_PASSWORD_NOT: "User hash password not generated",
        ROLE_NOT_EXIST: "User role not found",
        DEPARTMENT_NOT_EXIST: "User department not found",
        USER_NOT_ADDED: "User not added",
        USER_ADDED: "User added successfully",
        MAIL_NOT_SENT: "User mail not sended",
        MAIL_BLOCKED: "User mail is blocked",
        ACCOUNT_NOT_ACTIVE: "User account is not active",
        OTP_SENT: "OTP sent successfully. check your mail...",
        MAIL_ALREADY_VALIDATE: "User email is already validate",
        INVALID_OTP: "Invalid or expired OTP",
        PASSWORD_FORMATE_NOT_MATCH:
            "Password must be at least 8 characters long and contain at least 1 capital letter, 1 number, and 1 special character.",
        RESET_PASSWORD_CHECK:
            "Unable to find user.Something went wrong please try again later.",
        USER_NOT_EXIST: "User not exists",
        IP_BLOCKED: "Unauthorized: Your IP address is blocked.",
        IP_BLOCKED_LOGIN: "Unauthorized: Your IP address is blocked due to too many login attempts.",
        USER_PROFILE_UPDATE_SUCCESS: "Profile updated",
        USER_PROFILE_UPDATE_FAILED: "Profile update failed ",
        OLD_PASSWORD_NOT_MATCH: "old password not matched",
        OLD_NEW_PASSWORD_SHOULD_NOT_MATCH:
            "old and new password should not be same",
        PASSWORD_CHANGE: "Password changed successfully",
        PASSWORD_NOT_CHANGED: "Unable to change user Password",
        MAX_LOGIN_ATTEMPTS:
            "Your have reached login attempt limit. Please try again after 24 hours.",
        SESSION_FETCH_SUCCESS: "Login session fatched successfully",
        SESSION_FETCH_FAILED: "Failed to fetch Login sessions",
        SESSION_DELETE_SUCCESS: "session delete successfully",
        SESSION_DELETE_FAILED: "session delete failed",
        SESSION_DELETE_NOT_FOUND: "unable to delete session",
    },
    DEPARTMENT: {
        NAME_NOT_ENTER: "Please enter departmentName",
        DEPARTMENT_ADDED: "Department added successfully",
        DEPARTMENT_DELETE: "Department delete successfully",
        DEPARTMENT_DELETE_FAILED: "Department delete failed",
        DEPARTMENT_ID_NOT_FOUND: "Department id not found",
        DEPARTMENT_UPDATE: "Department updated successfully",
        DEPARTMENT_UPDATE_FAILED: "Failed to update department",
        DEPARTMENT_FETCH: "Department fetched successfully",
        DEPARTMENT_FETCH_FAILED: "Failed to fetch depatment",
        FETCH_KEYWORD: "Department keyword fetched successfully",
        FETCH_FAILED_KEYWORD: "Failed to fetch depatment keyword",
        DEPARTMENT_EXIST: "Department already exist",
    },
    MODULES_PERMISSIONS: {
        FETCH_SUCCESS: "Module permissions fetched successfully",
        FETCH_FAILED: "Failed to fetch module permissions",
    },
    MODULES_PERMISSIONS_USER: {
        FETCH_SUCCESS: "Module permissions fetched successfully for user",
        FETCH_FAILED: "Failed to fetch module permissions for user",
        ROLE_ID_NOT_FOUND: "Please enter user role id",
    },
    PERMISSIONS: {
        FETCH_SUCCESS: "permissions fetched successfully",
        FETCH_FAILED: "Failed to fetch permissions",
    },
    MODULES: {
        FETCH_SUCCESS: "Module fetched successfully",
        FETCH_FAILED: "Failed to fetch module ",
    },
    ROLES: {
        NAME_NOT_ENTER: "Please enter roleName",
        ENTER_ROLE_ID: "Please enter roleId",
        ROLE_ASSIGNED_ALREADY:
            "Unable to delete the role. This role is currently assigned to one or more users.",
        DEPARTMENT_ID_NOT_FOUND: "Please enter departmentId",
        FETCH_SUCCESS: "Roles fetched successfully",
        FETCH_FAILED: "Failed to fetch roles ",
        ADDED_SUCCESS: "Roles added successfully",
        ADDED_FAILED: "Failed to add roles",
        ROLE_ID_NOT_FOUND: "Roles id not found",
        DELETE_SUCCESS: "Roles delete successfully",
        DELETE_FAILED: "Failed to delete roles",
        ROLES_ID_NOT_FOUND: "Roles id not found",
        UPDATE_SUCCESS: "Roles updated successfully",
        UPDATE_FAILED: "Failed to update roles",
        ROLES_EXIST: "Role already exist",
    },
    ROLES_MODULE_PERMISSIONS: {
        FETCH_SUCCESS: "RolesModulePermissions fetched successfully",
        FETCH_FAILED: "Failed to fetch RolesModulePermissions ",
        ADDED_SUCCESS: "RolesModulePermissions added successfully",
        ADDED_FAILED: "Failed to add RolesModulePermissions",
        DELETE_SUCCESS: "RolesModulePermissions delete successfully",
        DELETE_FAILED: "Failed to delete RolesModulePermissions",
        UPDATE_SUCCESS: "RolesModulePermissions updated successfully",
        UPDATE_FAILED: "Failed to update RolesModulePermissions",
    },
    SERVICE: {
        NAME_NOT_ENTER: "Please enter service name",
        SERVICE_SLUG_NOT_ENTER: "Please enter slug",
        SERVICE_DEPARTMENT_NOT_SELECTED: "Please select department",
        SERVICE_ADDED: "Service added successfully",
        SERVICE_DELETE: "Service delete successfully",
        SERVICE_DELETE_FAILED: "Service delete failed",
        SERVICE_ID_NOT_FOUND: "Service id not found",
        SERVICE_UPDATE: "Service updated successfully",
        SERVICE_UPDATE_FAILED: "Failed to update service",
        SERVICE_FETCH: "Service fetched successfully",
        SERVICE_FETCH_FAILED: "Failed to fetch service",
        SERVICE_EXIST: "Service already exist",
    },
    CUSTOMER: {
        NOT_FOUND: "Customer not found. Please check your email and try again.",
        FETCH_SUCCESS: "Customer info fetched successfully",
        NIB_NUMBER_EXIST:
            "This NIB number is already in use with another customer. Please verify the information and try again.",
        EMAIL_EXIST: "This email already exists",
        FETCH_FAILED: "Failed to fetch Customer info",
        PASSWORD_INVALID:
            "Invalid password. Please check your password and try again.",
        INVALID_LINK:"Invalid link. Please check the link and try again.",
        UPDATE_SUCCESS: "Customer updated successfully",
        UPDATE_FAILED: "Failed to update Customer",
        NAME_NOT_ENTER: "Please enter name",
        EMAIL_NOT_ENTER: "Please enter email",
        ALREADY_EXIST: "Customer aleady exists",
        EMAIL_NOT_REGISTER: "Customer email not registered",
        DELETE_SUCCESS: "Customer delete successfully",
        DELETE_FAILED: "Customer delete failed",
        MAX_LOGIN_ATTEMPTS:
            "Your have reached login attempt limit. Please try again after 24 hours.",
        LOGIN: "Logged in!",
        MAIL_SENT: "Reset link has been successfully sent to the mail...",
        EMAIL_NOT_REGISTRED: "email is not registered with us....",
        PASSWORD_UPDATE: "Customer password updated successfully",
        IP_BLOCKED: "Unauthorized: Your IP address is blocked.",
        IP_BLOCKED_LOGIN: "Unauthorized: Your IP address is blocked due to too many login attempts.",        
        TOKEN_NOT_EXIST: "Customer token is not exist",
        PASS_NOT_MATCH: "Customer password is not matched!",
        EMAIL_NOT_MATCH: "Customer email not matched",
        HASH_PASSWORD_NOT: "Customer hash password not generated",
        CUSTOMER_NOT_ADDED: "Customer not added",
        CUSTOMER_ADDED: "Customer added successfully",
        MAIL_NOT_SENT: "Customer mail not sended",
        MAIL_BLOCKED: "Customer mail is blocked",
        ACCOUNT_NOT_ACTIVE: "Customer account is not active",
        OTP_SENT: "OTP sent successfully. check your mail...",
        MAIL_ALREADY_VALIDATE: "Customer email is already validate",
        INVALID_OTP: "Invalid or expired OTP",
        PASSWORD_FORMATE_NOT_MATCH:
            "Password must be at least 8 characters long and contain at least 1 capital letter, 1 number, and 1 special character.",
        RESET_PASSWORD_CHECK:
            "Unable to find customer.Something went wrong please try again later.",
        PROFILE_NOT_AUTHORIZED:
            "You are not authorized to login/set reset password access.you are linked with another customer",
       ACCOUNT_DELETED:
            "Your account has been deleted. You are not authorized to login/set reset password access.",
        SESSION_FETCH_SUCCESS: "Login session fatched successfully",
        SESSION_FETCH_FAILED: "Failed to fetch Login sessions",
        SESSION_DELETE_SUCCESS: "session delete successfully",
        SESSION_DELETE_FAILED: "session delete failed",
        SESSION_DELETE_NOT_FOUND: "unable to delete session",
        PASSWORD_CHANGE: "User password changed successfully",
        PASSWORD_NOT_CHANGED: "Unable to change user password",
        OLD_PASSWORD_NOT_MATCH: "old password not matched",
        OLD_NEW_PASSWORD_SHOULD_NOT_MATCH:
            "old and new password should not be same",
    },
    CUSTOMER_PROFILE: {
        NOT_FOUND:
            "Customer not found. Please check your customerId and try again.",
        FETCH_SUCCESS: "Customer profile list fetched successfully",
        FETCH_FAILED: "Failed to fetch Customer profile list",
        UPDATE_SUCCESS: "Customer profile updated successfully",
        UPDATE_FAILED: "Failed to update Customer profile",
        ALREADY_EXIST: "Customer aleady exists",
        DELETE_SUCCESS: "Customer profile delete successfully",
        DELETE_FAILED: "Customer profile delete failed",
        CUSTOMER_NOT_ADDED: "Failed to added customer profile",
        CUSTOMER_ADDED: "Customer profile added successfully",
        NAME_NOT_ENTER: "Please enter customer name",
        EMAIL_NOT_ENTER: "Please enter customer email",
        NIB_NUMBER_EXIST: "Please enter nibNumber email",
    },
    ADDRESS: {
        NAME_NOT_ENTER: "Please enter address name",
        ADDRESS_CUSTIOMER_ID_NOT_FOUND: "Customer not found this customerId",
        ADDRESS_CUSTIOMER_NOT_ENTER: "Please enter customerId",
        ADDRESS_DEPARTMENT_NOT_SELECTED: "Please select department",
        ADDRESS_ADDED: "Address added successfully",
        ADDRESS_DELETE: "Address delete successfully",
        ADDRESS_DELETE_FAILED: "Address delete failed",
        ADDRESS_ID_NOT_FOUND: "Address id not found",
        ADDRESS_UPDATE: "Address updated successfully",
        ADDRESS_UPDATE_FAILED: "Failed to update address",
        ADDRESS_FETCH: "Address fetched successfully",
        ADDRESS_FETCH_FAILED: "Failed to fetch address",
        ADDRESS_EXIST: "Address already exist",
    },
    COUNTRIES: {
        COUNTRIES_FETCH: "Countries data fetched successfully",
        COUNTRIES_FETCH_FAILED: "Failed to fetch countries data",
    },
    STATES: {
        STATES_FETCH: "State data fetched successfully",
        STATES_FETCH_FAILED: "Failed to fetch state data",
        COUNTRIES_STATES_NOT_FOUND: "No data found for select country",
    },
    ANNOUNCEMENT: {
        TITLE_NOT_ENTER: "Please enter title",
        DEPARTMENT_NOT_ENTER: "Please enter department",
        ANNOUNCEMENT_ADDED: "Announcement added successfully",
        ANNOUNCEMENT_DELETE: "Announcement delete successfully",
        ANNOUNCEMENT_DELETE_FAILED: "Announcement delete failed",
        ANNOUNCEMENT_ID_NOT_FOUND: "Announcement id not found",
        ANNOUNCEMENT_UPDATE: "Announcement updated successfully",
        ANNOUNCEMENT_UPDATE_FAILED: "Failed to update announcement",
        ANNOUNCEMENT_FETCH: "Announcement fetched successfully",
        ANNOUNCEMENT_FETCH_FAILED: "Failed to fetch announcement",
        ANNOUNCEMENT_EXIST: "Announcement already exist",
    },
    BANNER: {
        TITLE_NOT_ENTER: "Please enter bannerTitle",
        BANNER_ADDED: "Banner  added successfully",
        BANNER_DELETE: "Banner  delete successfully",
        BANNER_DELETE_FAILED: "Banner  delete failed",
        BANNER_ID_NOT_FOUND: "Banner  id not found",
        BANNER_UPDATE: "Banner  updated successfully",
        BANNER_UPDATE_FAILED: "Failed to update banner ",
        BANNER_FETCH: "Banner  fetched successfully",
        BANNER_FETCH_FAILED: "Failed to fetch banner",
        FETCH_KEYWORD: "Banner  keyword fetched successfully",
        FETCH_FAILED_KEYWORD: "Failed to fetch banner keyword",
        BANNER_EXIST: "Banner  already exist",
    },
    FAQ: {
        ADDED_SUCCESS: "FAQ added successfully",
        ADDED_FAILED: "Failed to add FAQ",
        DELETE_SUCCESS: "FAQ delete successfully",
        DELETE_FAILED: "Failed to delete FAQ",
        FAQ_ID_NOT_FOUND: "FAQ id not found",
        UPDATE_SUCCESS: "FAQ updated successfully",
        UPDATE_FAILED: "Failed to update FAQ",
        FAQ_EXIST: "FAQ already exist",
        FETCH_SUCCESS: "FAQ fetched successfully",
        FETCH_FAILED: "Failed to fetched FAQ",
    },
    TABLE_COLUMN_CONFIG: {
        ADDED_SUCCESS: "Table column config added successfully",
        ADDED_FAILED: "Failed to add table column config",
        UPDATE_SUCCESS: "Table column config updated successfully",
        UPDATE_FAILED: "Failed to update table column config",
        FETCH_SUCCESS: "Table column config fetched successfully",
        FETCH_FAILED: "Failed to fetched table column config",
        USER_ID_NOT_FOUND: "Please enter user id not found",
        TABLE_NAME_NOT_FOUND: "Plese enter table name",
        TABLE_USER_NOT_FOUND :"Plese enter table name and userId",
    },
    UPCOMING_EVENTS: {
        ADDED_SUCCESS: "Upcoming event added successfully",
        ADDED_FAILED: "Failed to add Upcoming event",
        DELETE_SUCCESS: "Upcoming event delete successfully",
        DELETE_FAILED: "Failed to delete Upcoming event",
        UPCOMING_EVENTS_ID_NOT_FOUND: "Upcoming event id not found",
        UPDATE_SUCCESS: "Upcoming event updated successfully",
        UPDATE_FAILED: "Failed to update Upcoming event",
        UPCOMING_EVENTS_EXIST: "Upcoming event already exist",
        FETCH_SUCCESS: "Upcoming event fetched successfully",
        FETCH_FAILED: "Failed to fetched Upcoming event",
    },
    FEEDBACK: {
        ADDED_SUCCESS: "Feedback added successfully",
        ADDED_FAILED: "Failed to add Feedback",
        FETCH_SUCCESS: "Feedback fetched successfully",
        FETCH_FAILED: "Failed to fetched Feedback",
    },
    KNOWLEDGE_BASE: {
        ADDED_SUCCESS: "KnowledgeBase added successfully",
        ADDED_FAILED: "Failed to add KnowledgeBase",
        DELETE_SUCCESS: "KnowledgeBase delete successfully",
        DELETE_FAILED: "Failed to delete KnowledgeBase",
        KNOWLEDGE_BASE_ID_NOT_FOUND: "KnowledgeBase id not found",
        UPDATE_SUCCESS: "KnowledgeBase updated successfully",
        UPDATE_FAILED: "Failed to update KnowledgeBase",
        KNOWLEDGE_BASE_EXIST: "KnowledgeBase already exist",
        FETCH_SUCCESS: "KnowledgeBase fetched successfully",
        FETCH_FAILED: "Failed to fetched KnowledgeBase",
        INVALID_KNOWLEDGE_BASE_ID: "Invalid KnowledgeBase id",
    },
    LIKE_DISLIKE: {
        ADDED_SUCCESS: "Like or Dislike added successfully",
        ADDED_FAILED: "Failed to add Like or Dislike",
        DELETE_SUCCESS: "Like or Dislike delete successfully",
        DELETE_FAILED: "Failed to delete Like or Dislike",
        LIKE_DISLIKE_ID_NOT_FOUND: "Like or Dislike id not found",
        UPDATE_SUCCESS: "Like or Dislike updated successfully",
        UPDATE_FAILED: "Failed to update Like or Dislike",
        LIKE_DISLIKE_EXIST: "Like or Dislike already exist",
        FETCH_SUCCESS: "Like or Dislike fetched successfully",
        FETCH_FAILED: "Failed to fetched Like or Dislike",
        INVALID_LIKE_DISLIKE_ID: "Invalid Like or Dislike id",
    },
    SUPPORT: {
        ADDED_SUCCESS: "Support message added successfully",
        ADDED_FAILED: "Failed to add Support message",
        FETCH_SUCCESS: "Support message fetched successfully",
        FETCH_FAILED: "Failed to fetched Support message",
    },
    SUPPORT_TYPE: {
        FETCH_SUCCESS: "Support type list fetched successfully",
        FETCH_FAILED: "Failed to fetched Support type list",
    },
    SYSTEM_SUPPORT: {
        ADDED_SUCCESS: "Your response added successfully",
        ADDED_FAILED: "Failed to add response",
    },
    WORKFLOW: {
        ADDED_SUCCESS: "Workflow added successfully",
        ADDED_FAILED: "Failed to add Workflow",
        UPDATE_SUCCESS: "Workflow update successfully",
        UPDATE_FAILED: "Failed to update Workflow",
        FETCH_SUCCESS: "Workflow fetched successfully",
        FETCH_SERVICES_ID_SUCCESS: "Workflow Ids fetched successfully",
        FETCH_FAILED: "Failed to fetched Workflow",
        WORKFLOW_NAME_NOT_FOUND: "Please enter workflow name",
        WORKFLOW_ID_NOT_FOUND: "Please enter workflowId",
        DELETE_SUCCESS: "Workflow record delete successfully",
        USER_NOT_FOUND: "Please enter userId",
    },
    BLOCKED_IP: {
        ADDED_SUCCESS: "BlockedIP added successfully",
        ADDED_FAILED: "Failed to add BlockedIP",
        DELETE_SUCCESS: "BlockedIP delete successfully",
        DELETE_FAILED: "Failed to delete BlockedIP",
        BLOCKED_IP_ID_NOT_FOUND: "BlockedIP id not found",
        UPDATE_SUCCESS: "BlockedIP updated successfully",
        UPDATE_FAILED: "Failed to update BlockedIP",
        BLOCKED_IP_EXIST: "BlockedIP already exist",
        FETCH_SUCCESS: "BlockedIP fetched successfully",
        FETCH_FAILED: "Failed to fetched BlockedIP",
    },
    AUDIT_LOG: {
        ADDED_SUCCESS: "Audit log added successfully",
        ADDED_FAILED: "Failed to add Audit log",
        FETCH_SUCCESS: "Audit log fetched successfully",
        FETCH_FAILED: "Failed to fetched Audit log",
        MISSING_REQUIRED_FIELDS: "Some fields are missing",
    },
    EMAIL_TEMPLATE: {
        ADDED_SUCCESS: "Email template added successfully",
        ADDED_FAILED: "Failed to add Email template",
        DELETE_SUCCESS: "Email template delete successfully",
        DELETE_FAILED: "Failed to delete Email template",
        UPDATE_SUCCESS: "Email template updated successfully",
        UPDATE_FAILED: "Failed to update Email template",
        FETCH_SUCCESS: "Email template fetched successfully",
        FETCH_FAILED: "Failed to fetched Email template",
    },
    EMAIL_LOGS: {
        ADDED_SUCCESS: "Email Log added successfully",
        ADDED_FAILED: "Failed to add Email Log",
        DELETE_SUCCESS: "Email Log delete successfully",
        DELETE_FAILED: "Failed to delete FAQ",
        FAQ_ID_NOT_FOUND: "Email Log not found",
        UPDATE_SUCCESS: "Email Log updated successfully",
        UPDATE_FAILED: "Failed to update Email Log",
        FAQ_EXIST: "Email Log already exist",
        FETCH_SUCCESS: "Email Logs fetched successfully",
        FETCH_FAILED: "Failed to fetched Email Logs",
    },
    GENERAL_SETTING:{
        CREATE_SUCCESS: "Settings created successfully",
        CREATE_FAILED: "Failed creating settings",
        FETCH_SUCCESS : "Setting fetched successfully",
        FETCH_FAILED: "Failed to fetch settings",
        UPDATE_SUCCESS : "Settings updated successfully",
        UPDATE_FAILED : "Failed to update settings"
    }
};

exports.USER_ROLES = {
    USER: "User",
    SUPER_ADMIN: "Super Admin",
    ADMIN: "Admin",
    CORE_USER: "Core User",
    DEPARTMENT_ADMIN: "Department Admin",
    DEPARTMENT_AGENT: "Department Agent",
};

exports.STATUS_CODES = {
    // 1XX INFORMATIONAL
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    EARLY_HINTS: 103,

    // 2XX SUCCESS
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
    IM_USED: 226,

    // 3XX REDIRECTION
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,

    // 4XX CLIENT ERROR
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    UNPROCESSABLE_ENTITY: 422,
    VALIDATION_ERROR: 422,
    NOT_VALID_DATA: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    UNORDERED_COLLECTION: 425,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,

    // 5XX SERVER ERROR
    SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
};
