exports.MESSAGES = {
  BAD_REQUEST: "Parameters not found",
  SERVER_ERROR: "Internal server error",
  VALIDATION: "Validation is not valid",
  AUTH_REQUIRE: "Authentication token required",
  INVALID_TOKEN: "Authentication token is not valid",
  VALID_TOKEN: "Authentication token is valid",
  BODY: "Please enter details",
  UPDATE_NOT: "Data not updated",
  UNAUTHORIZED_REQUEST: "You are not authorized for current action",
  EMPTY_PAYLOAD: "Payload is empty",
  DATA_NOT_FETCH: "Data not fetched",
  ID_NOT_FOUND: "Id not found",
  CHAT: {
    CHAT_CREATE: "chat created successfully",
    CHAT_PERSONAL_FETCH: "personal chat fetch successfully",
    CHAT_ARCHIVE: "chat archive successfully",
    CHAT_ARCHIVE_PERSONAL_FETCH : "personal archive chat fetch successfully",
    CHAT_ARCHIVE_GROUP_FETCH:"group archive chat fetch successfully",
    CHAT_FAVOURITE_PERSONAL_FETCH : "personal favourite chat fetch successfully",
    CHAT_FAVOURITE_GROUP_FETCH : "group favourite chat fetch successfully",
    GROUP_CHAT_NOT_FOUND:"group chat not found",
    CHAT_ARCHIVE_PERSONAL: "personal chat archive successfully",
    CHAT_UNARCHIVE: "chat unarchive successfully",
  
    CHAT_ARCHIVE_GROUP: "group chat archive successfully",
    CHAT_ARCHIVE_GROUP_FAILED: "Failed to archive group chat",
    CHAT_FAVOURITE: "chat favourite successfully",
    CHAT_UNFAVOURITE: "chat unfavourite successfully",
    CHAT_FAVOURITE_GROUP_FAILED: "Failed to favourite group chat",
    CHAT_UNSEEN_MESSAGE_COUNT: "unseen message count successfull",
    CHAT_UNSEEN_MESSAGE_COUNT_FAILED: "failed to get message unseen count",
    CHAT_NO_UNSEEN_MESSAGE_COUNT: "no unseen message count successfull",
    
    CHAT_GROUP_FETCH: "group chat fetch successfully",

    CHAT_MESSAGE_CREATE: "chat message created successfully",
    CHAT_FETCH_FAILED: "failed to fetch chat",
    CHAT_DELETE: "chat deleted successfully",
    CHAT_DELETE_GROUP: "group chat deleted successfully",

    CHAT_LEAVE: "chat leave successfully",

    CHAT_UPDATE: "chat updated successfully",
    CHAT_DELETE_FAILED: "failed to delete chat",
    CHAT_CONTENT_ATTACHMENT:
      "Either content or attachmentType must be provided to create a message",
    CHAT_ATTACHMENT_URL:
      "attachmentUrl must be provided when attachmentType is specified",
    FETCH_SUCCESS: "Documents fetched successfully",
    FETCH_FAILED: "Failed to fetch Documents ",
    LIST_FETCH_SUCCESS: "Documents list fetched successfully",
    LIST_FETCH_FAILED: "Failed to fetch Documents list ",
    ADDED_SUCCESS: "Documents added successfully",
    ADDED_FAILED: "Failed to add Documents",
    NAME_UPDATE_SUCCESS: "Document name  updated successfully",
    NAME_UPDATE_FAILED: "Failed to update document name",
    INVALID_REQUEST: "invalid request"
  },
};

exports.USER_ROLES = {
  USER: "User",
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  CORE_USER: "Core User",
  DEPARTMENT_ADMIN: "Department Admin",
  DEPARTMENT_AGENT: "Department Agent",
};

exports.STATUS_CODES = {
  // 1XX INFORMATIONAL
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,

  // 2XX SUCCESS
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  // 3XX REDIRECTION
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4XX CLIENT ERROR
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  UNPROCESSABLE_ENTITY: 422,
  VALIDATION_ERROR: 422,
  NOT_VALID_DATA: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  UNORDERED_COLLECTION: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5XX SERVER ERROR
  SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
};
